### ISSUE TITLE
Use widevine-other-locations patch for better Silverblue support

### ISSUE THREAD

**Issue by isheshukov** [qvint/ungoogled-chromium-fedora#3]
Hi!

Currently in chromium-browser-privacy if you want to install Widevine you need to copy files into root locations which is not possible in Fedora Silverblue.

[This](https://bazaar.launchpad.net/~chromium-team/chromium-browser/disco-dev/view/head:/debian/patches/widevine-other-locations) patch allows Chrome to search for Widevine in home dir location which would allow Silverblue users to use it.

**Comment by qvint** [comment]
Thanks for the report, I'll include the patch to the next release.
